services:
    api:
      build: .
      depends_on:
        - postgres
      ports:
        - 8000:8000
      volumes:
        - ./app:/usr/src/app/app:bind
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
        # env_file:
      #   - ./.env
      environment:
        - DATABASE_HOSTNAME=postgres
        - DATABASE_PORT=5432
        - DATABASE_PASSWORD=PqQyHy_56556500
        - DATABASE_NAME=fastapi
        - DATABASE_USERNAME=postgres
        - SECRET_KEY=HELLO
        - ALGORITHM=HS256
        - ACCESS_TOKEN_EXPIRE_MINUTES=60

    postgres:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=PqQyHy_56556500
        - POSTGRES_DB=fastapi
      
      volumes:
        - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db: