"""adding address and zip_code columns to users table

Revision ID: 69d557ba3f16
Revises: 9c1c56265896
Create Date: 2024-10-09 11:41:18.225560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d557ba3f16'
down_revision: Union[str, None] = '9c1c56265896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('zip_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
